# Generated by Django 6.0.3 on 2026-03-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'stacks',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('term', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('examples', models.TextField()),
                ('consclusions', models.TextField()),
                ('categories', models.ForeignKey(db_column='categories_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.categories')),
                ('stacks', models.ManyToManyField(blank=True, to='main.stacks')),
                ('tags', models.ManyToManyField(blank=True, to='main.tags')),
            ],
            options={
                'db_table': 'patterns',
                'unique_together': {('id', 'categories')},
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('edit_at', models.DateField(blank=True, null=True)),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
            ],
            options={
                'db_table': 'logs',
                'unique_together': {('id', 'patterns')},
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
                ('users', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.profiles')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('id', 'users', 'patterns')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
                ('users', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.profiles')),
            ],
            options={
                'db_table': 'comments',
                'unique_together': {('id', 'patterns', 'users')},
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('id', 'patterns')},
            },
        ),
        migrations.CreateModel(
            name='StackPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
                ('stacks', models.ForeignKey(db_column='stacks_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.stacks')),
            ],
            options={
                'db_table': 'stack_pattern',
                'unique_together': {('id', 'stacks', 'patterns')},
            },
        ),
        migrations.CreateModel(
            name='TagPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.ForeignKey(db_column='patterns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.patterns')),
                ('tags', models.ForeignKey(db_column='tags_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.tags')),
            ],
            options={
                'db_table': 'tag_pattern',
                'unique_together': {('patterns', 'tags')},
            },
        ),
    ]
