# Generated by Django 6.0.3 on 2026-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='edit_at',
        ),
        migrations.AlterField(
            model_name='logs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
