# Generated by Django 6.0.3 on 2026-03-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns',
            name='stacks',
            field=models.ManyToManyField(blank=True, to='main.stacks'),
        ),
        migrations.AddField(
            model_name='patterns',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tags'),
        ),
    ]
