# Generated by Django 6.0.3 on 2026-03-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_logs_edit_at_alter_logs_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('none', 'none'), ('like', 'like'), ('dislike', 'dislike')], db_column='status', default='none', max_length=10)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profiles')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratings')),
            ],
            options={
                'db_table': 'rating_profiles',
                'unique_together': {('id',)},
            },
        ),
    ]
