# Generated by Django 6.0.3 on 2026-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rating_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_profiles',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating_profiles',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
